site_name: Tvheadend 4.0

site_url: https://tvheadend.org

repo_url: https://github.com/tvheadend/tvheadend-documentation

copyright: (c) 2006 - 2015 Tvheadend Foundation CIC

theme: readthedocs

extra_css: 
    - custom.css

site_favicon: images/favicon.png

markdown_extensions:
    - smarty

pages:
    - Introduction:
        - index.md
        - Overview: overview.md
        - Basic Requirements: basic_requirements.md
        - Features: features.md
    - Getting Started:
        - Before you begin - some basic concepts: before_you_begin.md
        - Install your tuner hardware: install_tuner_hardware.md
        - Install Tvheadend: install_tvheadend.md
        - Configure Tvheadend: configure_tvheadend.md
    - Web Interface Guide:
        - General: webui_general.md
        - Electronic Program Guide Tab: webui/epg.md
        - Digital Video Recorder Tab:
            - Upcoming/Current Recordings: webui/dvr_upcoming.md
            - Finished Recordings: webui/dvr_finished.md
            - Failed Recordings: webui/dvr_failed.md
            - DVR AutoRec Entries: webui/dvr_autorec.md
            - Time Schedules: webui/dvr_timerec.md
        - Configuration Tab:
            - General: webui/config_misc.md
            - Access Entries: webui/config_access.md 
            - DVB Inputs:
                - TV Adapters: webui/config_tvadapters.md
                - Networks: webui/config_networks.md
                - Muxes: webui/config_muxes.md
                - Services: webui/config_services.md
                - Mux Schedulers: webui/config_muxsched.md
            - Channel/EPG:
                - Channel: webui/config_channels.md
                - Channel Tags: webui/config_tags.md
                - Bouquets: webui/config_bouquet.md
                - EPG Grabber: webui/config_epggrab.md
            - Stream:
                - Stream Profiles: webui/config_streamprofile.md
                - (Various) Stream Filters: webui/config_esfilter.md
            - Recording:
                - Digital Video Recorder Profiles: webui/config_dvr.md
                - Timeshift: webui/config_timeshift.md
            - CAs: webui/config_caclient.md
            - Debugging: webui/config_tvhlog.md
        - Status Tab:
            - Stream: webui/status_stream.md
            - Subscriptions: webui/status_subscriptions.md
            - Connections: webui/status_connections.md
            - Service Mapper: webui/status_servicemapper.md
        - About Tab: webui/about.md
    - Appendices:
        - Appendix 1 - Frequently-asked Questions: Appendices/faqs.md
        - Appendix 2 - Command-line Options: Appendices/command_line_options.md
        - Appendix 3 - Debugging Options: Appendices/debugging.md
        - Appendix 4 - Updating this documentation: Appendices/doc_update.md
        - Appendix 5 - Markdown Cribsheet: Appendices/markdown_cribsheet.md
    - About: about_project.md
